WCCILdata    (0), 2022.04.19 20:41:15.128, SYS,  INFO,        1, Manager Start, PROJ, BoilerTest1, V 3.15 - 3.15   platform Windows AMD64 linked at Jan 31 2019 19:30:43 (3914f9beaa1)
WCCILdata    (0), 2022.04.19 20:41:15.130, SYS,  INFO,        0, , (Re)Opening databases in single user mode without transaction logging.
WCCILdata    (0), 2022.04.19 20:41:15.479, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Initializing last value cache
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Loading internal datapoints
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Initializing ID history
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Initializing Alert history
WCCILdata    (0), 2022.04.19 20:41:15.480, SYS,  INFO,        0, , Initializing Alert Class cache
WCCILdata    (0), 2022.04.19 20:41:15.481, SYS,  INFO,        6, Initialization by Data Manager finished
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.arNr:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.state:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arType:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arName:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.createArchive:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.forwardToRDB:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errNum:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errDp:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errBit:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errRead:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheGet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.aliveInterval:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.saveCycle:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validFrom:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validUntil:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.time:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.weekDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.monthDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.month:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncTime:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncWeekDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncMonth:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.interval:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.delay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validFrom:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validUntil:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.time:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.weekDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.monthDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.month:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncTime:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncWeekDay:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.481, SYS,  SEVERE,    118, Last error already repeated 50 times. Until another output occurs, this one will be blocked.
WCCILdata    (0), 2022.04.19 20:41:15.482, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileCompression.autoStartAfterSwitchSet:_original.._value
WCCILdata    (0), 2022.04.19 20:41:15.482, SYS,  INFO,      119, Last error repeated 213 times.
WCCILdata    (0), 2022.04.19 20:41:15.482, SYS,  INFO,        0, , Initializing Value Archives
WCCILdata    (0), 2022.04.19 20:41:15.482, SYS,  INFO,        0, , ValueArchive will be used...
WCCILdata    (0), 2022.04.19 20:41:15.541, SYS,  INFO,        4, Connected to (SYS: 1 Event -num 0 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:15.543, SYS,  INFO,        0, , Manager (SYS: 1 Event -num 0 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:15.575, SYS,  INFO,        4, Connected to (SYS: 1 Driver -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:15.577, SYS,  INFO,        0, , Manager (SYS: 1 Driver -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:15.699, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:15.700, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:15.860, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:15.891, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:15.892, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:15.930, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:15.960, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:15.962, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:16.191, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:16.218, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:16.220, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:16.231, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:16.258, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:16.260, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:16.269, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:16.297, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:16.299, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:16.317, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:16.345, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:16.347, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:18.795, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:18.823, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:18.825, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:18.834, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:18.862, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:18.865, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:18.938, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:18.965, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ WIN-81JS8FENBF6 (::1)
WCCILdata    (0), 2022.04.19 20:41:18.967, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.19 20:41:18.976, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.19 20:41:20.995, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Driver -num 1 CONN: 1), Connection closed
WCCILdata    (0), 2022.04.19 20:41:21.095, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Event -num 0 CONN: 1), Connection closed
WCCILdata    (0), 2022.04.19 20:41:23.097, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2022.04.19 20:41:23.099, SYS,  INFO,        2, Manager Stop
